edition = "2021"
use_small_heuristics = "Max"
newline_style = "Unix"

indent_style = "Block"
hard_tabs = false

format_strings = true
brace_style = "PreferSameLine"
chain_width = 95

imports_granularity = "Module"
