[package]
name = "bad-apple"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.36.1", features = ["qemu", "global_allocator"] }
thiserror = { version = "2.0.17", default-features = false }
